### ISSUE TITLE
WebhookResponse doesn't check status correctly

### ISSUE THREAD

**Issue by rootpd** [tomaj/omnipay-viamo#1]
It looks like `sendData()` method of `WebhookRequest` doesn't check all necessary stuff it should be. It's not enough to check whether the `payment` object is present, but it's necessary to also check the actual status. 

https://github.com/tomaj/omnipay-viamo/blob/master/src/Viamo/Message/WebhookRequest.php#L96

Based on the specs, the enum of result is:

* `OK`
* `FAIL`
* `BANK_PROC`

And we've received at least one request with the payment info set and status `BANK_PROC`. I think it's necessary to check for explicit `OK` status before returning `success: true`.

**Comment by tomaj** [comment]
Fixed in version 1.0.0

**Comment by rootpd** [comment]
Had to reopen this, library is still not differentiating between `BANK_PROC` and `OK` statuses.

The payment is done only when the status is `OK`, otherwise it's still waiting in the bank for procession and can be postponed by 30+ minutes when bank day is over.

Maybe it should be configurable by client (whether you want to wait until it's fully processed or whether processing queue is fine for client), but the check of `payment.result` should be there.

This notification will almost always be followed by the following one tens of minutes later.

```javascript
{
  // ...
  "payment": {
    // ...
    "result": "BANK_PROC",
    "processedOn": "2018-05-25T22:05:40+0200",
    "currency": "EUR",
    // ...
  },
  // ...
}
```

```javascript
{
  // ...
  "payment": {
    // ...
    "result": "OK",
    "processedOn": "2018-05-25T22:33:29+0200",
    "currency": "EUR",
    // ...
  },
  // ...
}
```

**Comment by tomaj** [comment]
You can check validation here: https://github.com/tomaj/omnipay-viamo/blob/master/src/Viamo/Message/WebhookRequest.php#L100

Library creates only success response when result is "OK"
